
### ROBOT side
#odometry
ODOM_NMEA_HEADER =  '$MVPODOME' 
#geopose
GEOPOSE_NMEA_HEADER = 'MVPGPOSE' 
#lumne pwm report
LUMEN_NMEA_HEADER = 'MVPLUMEN'
WPT_RP_NMEA_HEADER = 'MVPWPTRP'
CTL_RP_NMEA_HEADER = 'MVPCTLRP'
HELM_RP_NMEA_HEADER = 'MVPHELMRP'
POW_RP_NMEA_HEADER = 'MVPPOWRP'

#gui side
LUMEN_SET_NMEA_HEADER = 'MVPLUMSET'
WPT_RQ_NMEA_HEADER = 'MVPWPTRQ'
CTL_RQ_NMEA_HEADER = 'MVPCTLRQ'
HELM_RQ_NMEA_HEADER = 'MVPHELMRQ'
POW_RQ_NEAM_HEADER = 'MVPPOWRQ'

#ROSTUFF
ROSCORE_NMEA_HEADER = 'MVPROSCORE'
ROS_LAUNCH_NMEA_HEADER = 'MVPLAUNCH'
ROS_NODE_LIST_NMEA_HEADER = 'MVPRNODELS'
ROS_TOPIC_LIST_NMEA_HEADER = 'MVPTPCLS'
ROS_TOPIC_FLTR_NEAM_HEADER = 'MVPTPCFR'


