name_space: alpha_img

##vehicle status
poses_source: odometry/filtered/local
geo_pose_source: odometry/geopose
vitals_source: power_monitor/power

#state services
get_state_service: helm/get_state
get_states_service: helm/get_states
change_state_service: helm/change_state


#mvp_controller service
controller_service: controller
controller_state_service: controller/get_state

##waypoints services
get_waypoints_service: helm/path_3d/get_next_waypoints
pub_waypoints_service: helm/path_3d/update_waypoints

##power manager
get_power_port_srv: gpio_manager/get_power_status
lumen_control_topic: gpio_manager/set_pwm_lumen_brightness


##remote ros manager
remote_host: "192.168.2.51"
remote_user: "mvp_admin"
remote_password: "temppwd"  

roslaunch_folder: ~/catkin_ws/src/alpha_img_auv/alpha_img_bringup/launch/
